// Generates src/components/icons.tsx from a local Font Awesome Free download.
// Usage: node scripts/build-icons.mjs /path/to/fontawesome-free-*-web
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.argv[2];
if (!root) throw new Error("Pass the Font Awesome Free web folder.");

// App-facing name → Font Awesome solid icon.
const icons = {
  Activity: "wave-square", ArrowDownUp: "arrow-down-wide-short", CalendarDays: "calendar-days",
  ChevronDown: "chevron-down", Clock3: "clock", Copy: "copy", Crosshair: "crosshairs",
  Database: "database", Filter: "filter", Gauge: "gauge-high", Heart: "heart",
  LocateFixed: "location-crosshairs", MapPin: "location-dot", Maximize2: "expand",
  Minimize2: "compress", Moon: "moon", Navigation: "location-arrow", Pause: "pause",
  Plane: "plane", PlaneLanding: "plane-arrival", PlaneTakeoff: "plane-departure", Play: "play",
  Radio: "tower-broadcast", Search: "magnifying-glass", Share2: "share-nodes",
  ShieldAlert: "shield-halved", Sun: "sun", X: "xmark",
};

const entries = Object.entries(icons).map(([name, file]) => {
  const svg = readFileSync(join(root, "svgs/solid", `${file}.svg`), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  const paths = [...svg.matchAll(/<path[^>]* d="([^"]+)"/g)].map((match) => match[1]);
  return `export const ${name} = createIcon("${name}", "${viewBox}", ${JSON.stringify(paths)});`;
});

writeFileSync("src/components/icons.tsx", `// Generated by scripts/build-icons.mjs. Do not edit by hand.
// Icons: Font Awesome Free 7 (solid) by Fonticons, Inc., CC BY 4.0. https://fontawesome.com/license/free
import { createIcon } from "./Icon";

${entries.join("\n")}
`);
console.log(`Wrote ${entries.length} icons.`);
